# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.CharField(max_length=200),
        ),
    ]
