# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lectut', '0002_auto_20170402_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='docfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
