# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectut', '0004_auto_20170502_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(related_name='unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
